/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_bank;
    
import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class setor extends javax.swing.JFrame {
       int saldo = 1000000;
    /**
     * Creates new form setor
     */
    public setor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        setor = new javax.swing.JTextField();
        Ok = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        EXIT1 = new javax.swing.JButton();
        HOME = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PENYETORAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 140, 50);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Masukkan Jumlah Setoran");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 80, 170, 20);

        setor.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        getContentPane().add(setor);
        setor.setBounds(130, 110, 140, 30);

        Ok.setText("SETOR");
        Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OkActionPerformed(evt);
            }
        });
        getContentPane().add(Ok);
        Ok.setBounds(160, 160, 70, 30);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(204, 255, 255));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("EXIT");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 28, 26, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("HOME");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(157, 28, 33, 15);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(100, 220, 200, 70);

        EXIT1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EXIT1.setText("<");
        EXIT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT1ActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT1);
        EXIT1.setBounds(10, 240, 80, 30);

        HOME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        HOME.setText(">");
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        jPanel1.add(HOME);
        HOME.setBounds(310, 240, 80, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 310);

        setSize(new java.awt.Dimension(416, 348));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        

// TODO add your handling code here:
    }//GEN-LAST:event_setorActionPerformed

    private void OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OkActionPerformed
       String setoran = setor.getText();
        int jmlsetor = Integer.parseInt(setoran); 
        int saldoakhir = saldo+jmlsetor;   
        if (jmlsetor%100!=0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM tidak menerima uang koin \nSilahkan ulangi kembali!", "Transaksi Gagal", 0);
        } else if (jmlsetor<50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal setor tunai adalah Rp 50.000,00", "ERROR", 0);
        }else if (jmlsetor>=50000) {
            JOptionPane.showMessageDialog(null, "Terima kasih telah melakukan penyetoran uang. Jumlah saldo terakhir adalah Rp " + saldoakhir);
            JOptionPane.showConfirmDialog(null,"Melanjutkan transaksi lain?","", JOptionPane.YES_NO_OPTION, 3);
        }
// TODO add your handling code here:
    }//GEN-LAST:event_OkActionPerformed
        public int getsaldo() {
       return saldo;
    }
    
    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
         new home().show();
               this.dispose();
    }//GEN-LAST:event_HOMEActionPerformed

    private void EXIT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT1ActionPerformed
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_EXIT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(setor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new setor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT1;
    private javax.swing.JButton HOME;
    private javax.swing.JButton Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField setor;
    // End of variables declaration//GEN-END:variables

   
}
