/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class tarik extends javax.swing.JFrame {

    int saldo = 1000000;
    /**
     * Creates new form tarik
     */
    public tarik() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TARIKAN = new javax.swing.JTextField();
        HOME = new javax.swing.JButton();
        TARIK1 = new javax.swing.JButton();
        EXIT1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 255, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 21)); // NOI18N
        jLabel1.setText("TARIK TUNAI");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(130, 20, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Jumlah uang :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(30, 80, 100, 30);

        TARIKAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TARIKANActionPerformed(evt);
            }
        });
        jPanel1.add(TARIKAN);
        TARIKAN.setBounds(140, 80, 230, 30);

        HOME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        HOME.setText(">");
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        jPanel1.add(HOME);
        HOME.setBounds(320, 220, 80, 30);

        TARIK1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        TARIK1.setText("TARIK");
        TARIK1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TARIK1ActionPerformed(evt);
            }
        });
        jPanel1.add(TARIK1);
        TARIK1.setBounds(160, 140, 80, 30);

        EXIT1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EXIT1.setText("<");
        EXIT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT1ActionPerformed(evt);
            }
        });
        jPanel1.add(EXIT1);
        EXIT1.setBounds(20, 220, 80, 30);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("EXIT");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 28, 26, 15);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("HOME");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(157, 28, 33, 15);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(110, 200, 200, 70);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 420, 310);

        setSize(new java.awt.Dimension(437, 347));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TARIKANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TARIKANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TARIKANActionPerformed

    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
            new home().show();
            this.dispose();
    }//GEN-LAST:event_HOMEActionPerformed

    private void TARIK1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TARIK1ActionPerformed
        String tarikan = TARIKAN.getText();
        
        int jmltarik = Integer.parseInt(tarikan);
        int saldoakhir = saldo-jmltarik;
        if (jmltarik%100!=0) {
            JOptionPane.showMessageDialog(null, "Mesin ATM tidak menerima penarikan berupa uang koin \nSilahkan ulangi lagi", "Transaksi Gagal", 0);
        }else if (jmltarik>=saldo) {
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi \nSilahkan lakukan penyetoran tunai", "Transaksi Gagal", 0);
        }else if (jmltarik<50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal pengambilan adalah Rp 50.000,00 ","Transaksi Gagal",0);
        }else{
            JOptionPane.showMessageDialog(null, "Terima kasih telah melakukan penarikan uang. Jumlah saldo terakhir adalah " + saldoakhir);
            if (saldoakhir<50000) {
                JOptionPane.showMessageDialog(null, "Saldo minimal Rp 50.000,00 Segera lakukan penyetoran untuk menghindari penutupan akun.","CAUTION",2);
            }
        } 
// TODO add your handling code here:
    }//GEN-LAST:event_TARIK1ActionPerformed
    int getsaldo() {
        return saldo;
    }
    
    private void EXIT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT1ActionPerformed
        dispose();
        
// TODO add your handling code here:
    }//GEN-LAST:event_EXIT1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tarik.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tarik().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT1;
    private javax.swing.JButton HOME;
    private javax.swing.JButton TARIK1;
    private javax.swing.JTextField TARIKAN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    void menabung(int saldo, String setoran) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
