/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_bank;

import javax.swing.JOptionPane;

/**
 *
 * @author Asus
 */
public class transfer extends javax.swing.JFrame {

    int saldo = 1000000;
    /**
     * Creates new form transfer
     */
    public transfer() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        transfer = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Transfer = new javax.swing.JButton();
        HOME = new javax.swing.JButton();
        EXIT1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        no = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        transfer.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        getContentPane().add(transfer);
        transfer.setBounds(130, 160, 140, 30);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Masukkan Jumlah Transferan");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(110, 130, 190, 20);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PENYETORAN");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 10, 140, 50);

        Transfer.setText("TRANSFER");
        Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TransferActionPerformed(evt);
            }
        });
        getContentPane().add(Transfer);
        Transfer.setBounds(140, 200, 110, 30);

        HOME.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        HOME.setText(">");
        HOME.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HOMEActionPerformed(evt);
            }
        });
        getContentPane().add(HOME);
        HOME.setBounds(310, 260, 80, 30);

        EXIT1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        EXIT1.setText("<");
        EXIT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EXIT1ActionPerformed(evt);
            }
        });
        getContentPane().add(EXIT1);
        EXIT1.setBounds(10, 260, 80, 30);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("EXIT");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(10, 28, 26, 15);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("HOME");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(157, 28, 33, 15);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(100, 240, 200, 70);

        no.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noActionPerformed(evt);
            }
        });
        getContentPane().add(no);
        no.setBounds(130, 90, 140, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Masukkan No Rekening");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(130, 60, 170, 20);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 330, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 400, 330);

        setSize(new java.awt.Dimension(416, 366));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_transferActionPerformed

    private void TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TransferActionPerformed
         String transferan = transfer.getText();
         String norek = no.getText();
        
        int jmltransfer = Integer.parseInt(transferan);
        int rek = Integer.parseInt(norek);
        int saldoakhir = saldo-jmltransfer;
        if (jmltransfer>=saldo) {
            JOptionPane.showMessageDialog(null, "Saldo anda tidak mencukupi \nSilahkan lakukan penyetoran", "Transaksi Gagal", 0);
        }else if (jmltransfer<50000) {
            JOptionPane.showMessageDialog(null, "Besaran minimal transfer tunai adalah Rp 50.000,00 ","Transaksi Gagal",0);
        }else{
            JOptionPane.showMessageDialog(null, "Terima kasih telah melakukan transfer \n ke No.Rek :"+ rek +" \n Jumlah saldo terakhir adalah " + saldoakhir);
            if (saldoakhir<50000) {
                JOptionPane.showMessageDialog(null, "Saldo minimal Rp 50.000,00 Segera lakukan penyetoran untuk menghindari penutupan akun.","CAUTION",2);
            }
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_TransferActionPerformed
        int getsaldo() {
        return saldo;
    }
    
    private void HOMEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HOMEActionPerformed
        new home().show();
        this.dispose();
    }//GEN-LAST:event_HOMEActionPerformed

    private void EXIT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EXIT1ActionPerformed
        dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_EXIT1ActionPerformed

    private void noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(transfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new transfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EXIT1;
    private javax.swing.JButton HOME;
    private javax.swing.JButton Transfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField no;
    private javax.swing.JTextField transfer;
    // End of variables declaration//GEN-END:variables
}
